### ISSUE TITLE
text→感情 apiの調査と，使い方

### ISSUE THREAD

**Issue by chigichan24** [chigichan24/MotherWeatherNewsServer#1]
- Pythonでどういう感じに叩くかを調べる．

**Comment by ishowta** [comment]
Azure Face API
  - Document
    - https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236
  - PythonのQuickStart
    - https://docs.microsoft.com/ja-jp/azure/cognitive-services/face/quickstarts/python

Cloud Natural Language API (documents.analyzeSentiment)
  - Document
    - https://cloud.google.com/natural-language/docs/reference/rest/v1/documents/analyzeSentiment
