### ISSUE TITLE
それぞれのemotion値からweatherを推定する式を作る

### ISSUE THREAD

**Issue by ishowta** [chigichan24/MotherWeatherNewsServer#16]
### 顔画像から
- {'anger','contempt','disgust','fear','happiness','neutral','sadness','surprise'}
- 「怒り」「軽蔑」「嫌悪」「恐怖」「幸福」「中立」「悲しみ」「驚き」
- それぞれ0~1

気分がいい時：happiness高い
どちらでもない：neutralが高い
気分が悪いとき：それ以外？
※slack参考

### テキストから
- {'magnitude','score'}
- score: -1~1
- score : -1...悪い 1...良い
- magnitude :
※[解釈の仕方](https://cloud.google.com/natural-language/docs/basics#interpreting_sentiment_analysis_values)
- 引用　「ドキュメントの感情分析の score は、ドキュメントの全体的な感情を示します。ドキュメントの感情分析の magnitude は、そのドキュメントに感情的な内容がどのくらい含まれているかを示します。この値は、ドキュメントの長さに比例する傾向があります。」

magnitudeはいらない？

どんな言葉？？

**Comment by chigichan24** [comment]
基本的に値を蓄積していく形でいいかなと思ってる．例えば，
``` diff = 2.5 * anger + contempt *  1.8 + disgused * 2.5 + 0.5 * fear - 2.0 * happiness -1.5 * nutral ```
みたいなある時点での画像の評価値を計算して，
これをサーバでリクエストが来るたびに足していく感じにするとかどうでしょう？という案が出ています

**Comment by chigichan24** [comment]
`state += diff`
で，stateが実質的にtempertureになり，この温度(というか，ここでは怒りの指標)によって，天気を判別する感じ．

**Comment by chigichan24** [comment]
`diff` が大きい時は，瞬間的な変化率が大きい時なので警報を打つ．

**Comment by ishowta** [comment]
あまりイメージできなくて、基本diffのモデルは悪くないのかもしれませんが、
少なくとも説教が発生した場合、無限にstateが増えていきませんか？

**Comment by chigichan24** [comment]
確かに，上限が設定できないという問題はありますね．

**Comment by chigichan24** [comment]
前回と今回の値の割合を決めて和を取るという方法を取れば上限は決まりますね(例えば前回の値*0.3 + 今回の値*0.7みたいな)

**Comment by ishowta** [comment]
さっきまでテキストのことしか考えてなかったんですが、
顔認識の場合、怒った顔が続くとtempletureが増えていくってのも違和感があるような

**Comment by chigichan24** [comment]
割合で取れば上限は決まるのでずっと増えていくという感じはなさそう．

**Comment by kinironote** [comment]
今このissueについて書いていますか？
